### ISSUE TITLE
Doesn't show view when we have multiple views and when we added it on any of subview.

### ISSUE THREAD

**Issue by Sahilberi** [Hassan-Aftab/HADropDown#1]
Hi,
     You did great job but their is big issue in this. when we add HADropDown in any of subview( callled it first view) and any another subview lays with first view then it goes background of second subview and if second view is tableview then it doesn't work at all. 
![screen shot 2017-03-09 at 4 46 08 pm](https://cloud.githubusercontent.com/assets/7422405/24041156/24e15466-0b32-11e7-9222-272b3a54f17c.png)

**Comment by Sahilberi** [comment]
resolved issue 
https://github.com/Sahilberi/HADropDown/blob/patch-1/HADropDown/HADropDown/HADropDown.swift

**Comment by Hassan-Aftab** [comment]
Hi,

Thank you very much for resolving this issue. Please generate a pull request and I will add you as collaborator in this project

**Comment by Sahilberi** [comment]
sure buddy :)
