### ISSUE TITLE
You cannot select the last item in the menu

### ISSUE THREAD

**Issue by cwilliamsz** [Hassan-Aftab/HADropDown#10]
Hi, you cannot select the last menu option due to the method below that adds a view footer that overlaps the last item.

To remove this method or comments it works normally the selection of options.

`func tableView(_ tableView: UITableView, viewForFooterInSection section: Int) -> UIView? {
        return UIView()
    }`

**Comment by Sahilberi** [comment]
you can resolve this problem by implementing heightForFooterInSection method. actually, it is taking default height of footer so when we press on the last cell we are actually pressing on the footer. so give height 0 to the footer.

func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
return 0.0
}
[https://github.com/Hassan-Aftab/HADropDown/issues/8](url)

**Comment by cwilliamsz** [comment]
I solved by removing the method that calls the viewForFooterInSection.

**Comment by Sahilberi** [comment]
That also works because table views would automatically resize the heights of footers to 0 for sections where tableView(_:viewForFooterInSection:) returned a nil view.
