### ISSUE TITLE
scroll error 

### ISSUE THREAD

**Issue by ahmedAsoliman** [Hassan-Aftab/HADropDown#12]
when user scroll the screen the list of items still in the old place 
which it appears on the first time

**Comment by Sahilberi** [comment]
can you please add the screenshots?

**Comment by ahmedAsoliman** [comment]
![36834039_1863103570378884_320266979594207232_n](https://user-images.githubusercontent.com/33735463/43366632-65226f2c-9341-11e8-903a-84c3b09e0936.png)

**Comment by Sahilberi** [comment]
Hi, @ahmedAsoliman there was an issue in the code. you need to replace                 self.superview?.insertSubview(view, belowSubview: table) line  with rootView?.insertSubview(view, belowSubview: table) in HADropDown file. Thanks!

**Comment by ahmedAsoliman** [comment]
same error
