### ISSUE TITLE
Dropdown items are not clickable in mac mini.

### ISSUE THREAD

**Issue by Hariss096** [Hassan-Aftab/HADropDown#14]
So one of my team member was working on a macbook and the dropdown is working perfectly fine there. But when I ran the same project in the exact same configuration (iOS 11.2, Xcode version 9.4, swift 4) on mac mini, the dropdown items are simply not clickable. We also have a uibutton behind dropdown items which gets clicked if we click that particular dropdown over that button. It acts as if the dropdown items are gone behind the safe area. I think there is an issue with the library because my code is working fine on laptop.

**Comment by Hassan-Aftab** [comment]
I think this issue is related to your view hierarchy. You must have added dropdown in a subview above your ui button, thats why you are unable to click it
