### ISSUE TITLE
[SELF-SOLVED] Deselect row and return to default state

### ISSUE THREAD

**Issue by rursache** [Hassan-Aftab/HADropDown#4]
solution:

**HADropDown**
```
var defaultLabel: String = String()

override func layoutSubviews() {
...
self.defaultLabel = label.text!
...
}

func deselectCell() {
	selectedIndex = -1
	label.text = self.defaultLabel
}
```

now just call

`self.dropdown.deselectCell()`

and selected cell will deselect and dropdown will show again the title/selection text

**Comment by iPhoNewsRO** [comment]
solution:

**HADropDown**
```
var defaultLabel: String = String()

```
override func layoutSubviews() {
...
textAllignment = .center
**self.defaultLabel = label.text!**
...
}
```

func deselectCell() {
	selectedIndex = -1
	label.text = self.defaultLabel
}
```

now just call

`self.dropdown.deselectCell`
