### ISSUE TITLE
Last cell only clickable after scrolling drop down

### ISSUE THREAD

**Issue by arpitjain03** [Hassan-Aftab/HADropDown#8]
Please help in resolving this issue

**Comment by daviddelmonte** [comment]
I have workaround -- add a blank cell to the end of the table

**Comment by arpitjain03** [comment]
It will show empty cell then

**Comment by Sahilberi** [comment]
@arpitjain03  @daviddelmonte  you can resolve this problem by implementing heightForFooterInSection  method. actually, it is taking default height of footer so when we press on the last cell we are actually pressing on the footer. so give height 0 to the footer.

func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
    return 0.0
  }

**Comment by arpitjain03** [comment]
Thanks @Sahilberi  It worked for me

**Comment by daviddelmonte** [comment]
Brilliant. Thanks!
