### ISSUE TITLE
DropDown views does not get removed

### ISSUE THREAD

**Issue by arpitjain03** [Hassan-Aftab/HADropDown#9]
If I navigate to another controller, from the controller in which HADropDown is used it does not get removed. May be this is because of adding it on window. Even dropDown.removeFromSuperview() does n't work. Help me in the same.
Thanks in advance.

**Comment by Sahilberi** [comment]
Hi @arpitjain03, we are removing topmost view in collapseTableView func. so,  I guess this problem shouldn't occur. can you debug is this function is calling or not?

func collapseTableView() {
    
    if isCollapsed {
      UIView.animate(withDuration: 0.25, animations: {
        self.table.frame = CGRect(x: self.tableFrame.origin.x, y: 
        self.tableFrame.origin.y+self.frame.height, width: self.frame.width, height: 0)
      })
      
      var rootView = self.superview
      while rootView?.superview != nil {
        rootView = rootView?.superview
      }
      
      rootView?.viewWithTag(99121)?.removeFromSuperview()
      
      if delegate != nil {
        delegate.didHide(dropDown: self)
      }
    }
  }
}

**Comment by arpitjain03** [comment]
It gets called but the view doesn't get removed. After this If i select any row it gets disappeared

**Comment by Sahilberi** [comment]
Can you show the code where are navigating to another controller? I mean if you tap outside the table view, tableview should collapse.

**Comment by arpitjain03** [comment]
Yeah you are right if i tap outside the tableview it collapse. But my case
is i opened the drop down and clicked on a button which navigates me to
next screen. Then the dropdown still remains there.
I navigated using : 
  self.navigationController?.pushViewController(viewController!,animated: true)

**Comment by Sahilberi** [comment]
Which button you are tapping ? can you share screenshots? I mean if HADropDown shows it will show in topmost view. so, there should be no button.
Ideally, you can click on three views:
 - The topmost view which is a window object.
 - on HADropDown view
 - on a table view cell

**Comment by arpitjain03** [comment]
Hello Sorry for late reply

![issue_hadropdown](https://user-images.githubusercontent.com/30592234/33819465-999c3822-de70-11e7-8c58-b7c9d2fa5d49.gif)

I liked your control very much, this is the issue I am still facing. If you can help me resolve this. It would be great.

**Comment by Sahilberi** [comment]
Can you share this demo project link?
